### ISSUE TITLE
multiclusterdeployments placementPolicy setting conditions issue

### ISSUE THREAD

**Issue by 00ahui** [moule3053/mck8s#1]
https://github.com/moule3053/mck8s/blob/56df1e2cd95ef5f3ef3327e7b7c110c2d9b8d226/multi-cluster-scheduler/multiclusterscheduler.py#L43

Should be:  when "locations" in spec, placement_policy = 'cluster_affinity'

**Comment by moule3053** [comment]
Thanks for using mck8s and pointing this out. Fixed!
