### ISSUE TITLE
node resource check not proper for single node k8s cluster

### ISSUE THREAD

**Issue by 00ahui** [moule3053/mck8s#2]
https://github.com/moule3053/mck8s/blob/56df1e2cd95ef5f3ef3327e7b7c110c2d9b8d226/multi-cluster-scheduler/utils.py#L230
https://github.com/moule3053/mck8s/blob/56df1e2cd95ef5f3ef3327e7b7c110c2d9b8d226/multi-cluster-scheduler/utils.py#L325

The lines only compute the available resources from node 1, suggest to check all nodes:
for node in core_v1.list_node(_request_timeout=timeout).items:

-----------

https://github.com/moule3053/mck8s/blob/56df1e2cd95ef5f3ef3327e7b7c110c2d9b8d226/multi-cluster-scheduler/utils.py#L382
https://github.com/moule3053/mck8s/blob/56df1e2cd95ef5f3ef3327e7b7c110c2d9b8d226/multi-cluster-scheduler/utils.py#L383

The lines use the node 1 to getPerNodeResources, suggest to use node 0:
        perNodeCPU = Q_(nodes.items[0].status.capacity['cpu']).to('m')
        perNodeMemory = Q_(nodes.items[0].status.capacity['memory']).to('Ki')

**Comment by moule3053** [comment]
The problem here is that for multi-node clusters it will give the wrong capacity and will create problems.

**Comment by 00ahui** [comment]
ok, thanks
