### ISSUE TITLE
Typo error in cloud-cluster-provisioner-autoscaler/Dockerfile

### ISSUE THREAD

**Issue by 00ahui** [moule3053/mck8s#3]
https://github.com/moule3053/mck8s/blob/56df1e2cd95ef5f3ef3327e7b7c110c2d9b8d226/cloud-cluster-provisioner-autoscaler/Dockerfile#L9

COPY configure_cilium_1.sh configure_cilium_2.sh ./
RUN chmod +x configure_cilium_1.sh
RUN chmod +x configure_cilium_2.sh

**Comment by moule3053** [comment]
Fixed!
